### ISSUE TITLE
Push new release to PyPi

### ISSUE THREAD

**Issue by gottsman** [calmh/unifi-api#29]
Can you add push a new release to PyPi which now includes the Python 3 support?

**Comment by gottsman** [comment]
Bump

**Comment by schinken** [comment]
Somethings weird with the version in PyPi. 

unifi===fatal-.Not.a.git.repository.-or.any.parent.up.to.mount.point.-tmp-Stopping.at.filesystem.boundary.-GIT-DISCOVERY-ACROSS-FILESYSTEM.not.set-.

**Comment by calmh** [comment]
:+1: uploaded 1.2.3
