### ISSUE TITLE
Is it working with UniFi 4.7.5 ?

### ISSUE THREAD

**Issue by soamz** [calmh/unifi-api#40]
Hi, has it been tested with UniFi 4.7.5 ??

**Comment by uJIu4** [comment]
i think not, v4 use different api.

**Comment by soamz** [comment]
Any other API which you know which works with v4.7.5 ?

**Comment by uJIu4** [comment]
No. But I'm going to try to write itself v4 support for this library. I will use this library to work.

**Comment by soamz** [comment]
Are you on Skype or Hangouts ?

**Comment by uJIu4** [comment]
cs_ujiu4 - skype

**Comment by soamz** [comment]
Added you to my skype

**Comment by oza4h07** [comment]
With a 4.7.5 setup, I'm getting this
unifi-ls-clients -c 192.168.1.243 -u foo -p secret -v v4 -s default
Traceback (most recent call last):
  File "/usr/local/bin/unifi-ls-clients", line 19, in <module>
    ap_names = dict([(ap['mac'], ap['name']) for ap in aps])
KeyError: 'name'

@soamz: Are you getting thinks like this ?
@uJIu4 : What do you mean by "v4 use different api" ? That -v v4 argument is not supported at the moment ?

**Comment by uJIu4** [comment]
Oh, i was wrong... :( api are support v4
In your case, one of your ap haven't name

**Comment by ehk20** [comment]
Can confirm v4 mostly works and this should be an easy fix with an ap.get:
ap_names = dict([(ap['mac'],ap.get('name','Unknown')) for ap in aps])

**Comment by calmh** [comment]
AFAIK this is resolved now
