### ISSUE TITLE
KeyError 'rssi'

### ISSUE THREAD

**Issue by sipvoip** [calmh/unifi-api#46]
This used to work, but I think it broke because I added some ethernet switches to the system so now some clients don't have rssi (just a guess). I would like it to show all clients, both wireless and wired if possible.

root@maggie unifi-api # ./unifi-ls-clients 
Traceback (most recent call last):
  File "./unifi-ls-clients", line 21, in <module>
    clients.sort(key=lambda x: -x['rssi'])
  File "./unifi-ls-clients", line 21, in <lambda>
    clients.sort(key=lambda x: -x['rssi'])
KeyError: 'rssi'

**Comment by staze** [comment]
crap, I just ran into this... boo! And here I thought ubiquiti broke things with their latest controller version. =(
